-- CreateEnum
CREATE TYPE "UserType" AS ENUM ('ADMIN', 'MEMBER', 'MACHINE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "type" "UserType" NOT NULL DEFAULT 'MEMBER',
ADD COLUMN     "updateDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
